# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# site info
title: Jaehee Park
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Jaehee. Welcome to my blog.
author_name: "Jaehee Park" # change this to your name
logo_url: https://user-images.githubusercontent.com/1294065/118412368-8db0e800-b667-11eb-9e0c-bc651457bf0f.png
# https://drive.google.com/file/d/13Ty61JxowRP1aWF9g94U8mzYAsahk588/view?usp=sharing # from drive
# https://secure.gravatar.com/avatar/cd1c8a88abe14148de73fdc85835b1f1   # from gravatar
# "../assets/happy_bean.png"
# https://avatars.githubusercontent.com/u/1294065?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# site settings
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jaeheejp
github_username:  jhpark1013
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
